# Generated by Django 4.2.6 on 2023-11-06 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAficiones',
            fields=[
                ('cv_aficion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_aficion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoApellidosMaterno',
            fields=[
                ('cv_ape_mat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_mat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoApellidosPaterno',
            fields=[
                ('cv_ape_pat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_pat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDirecciones',
            fields=[
                ('cv_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoGeneros',
            fields=[
                ('cv_genero', models.AutoField(primary_key=True, serialize=False)),
                ('ds_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoNombres',
            fields=[
                ('cv_nombre', models.AutoField(primary_key=True, serialize=False)),
                ('ds_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTiposPersona',
            fields=[
                ('cv_tp_person', models.AutoField(primary_key=True, serialize=False)),
                ('ds_tp_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTrabajos',
            fields=[
                ('cv_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('ds_trabajo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_usuario',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Cuenta activa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cv_persona', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono de la persona')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas de la persona')),
                ('cv_aficion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.catalogoaficiones', verbose_name='Aficion')),
                ('cv_ape_mat', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidosmaterno', verbose_name='Apellido materno')),
                ('cv_ape_pat', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidospaterno', verbose_name='Apellido paterno')),
                ('cv_direccion', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogodirecciones', verbose_name='Direccion')),
                ('cv_genero', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogogeneros', verbose_name='Genero')),
                ('cv_nombre', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogonombres', verbose_name='Nombre')),
                ('cv_tp_persona', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotipospersona', verbose_name='Tipo de persona')),
                ('cv_trabajo', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotrabajos', verbose_name='Trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.persona'),
        ),
    ]
