# Generated by Django 4.2.6 on 2023-10-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
