# Generated by Django 4.2.6 on 2023-10-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_catalogoaficiones_catalogoapellidosmaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='security.persona'),
        ),
    ]
