# Generated by Django 4.2.6 on 2023-10-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_customuser_fecha_fin_customuser_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAficion',
            fields=[
                ('cv_aficion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_aficion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoApellidoPaterno',
            fields=[
                ('cv_ape_pat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_pat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDireccion',
            fields=[
                ('cv_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoGenero',
            fields=[
                ('cv_genero', models.AutoField(primary_key=True, serialize=False)),
                ('ds_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoNombre',
            fields=[
                ('cv_nombre', models.AutoField(primary_key=True, serialize=False)),
                ('ds_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTipoPersona',
            fields=[
                ('cv_tp_person', models.AutoField(primary_key=True, serialize=False)),
                ('ds_tp_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTrabajo',
            fields=[
                ('cv_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('ds_trabajo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cv_persona', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono de la persona')),
                ('email', models.EmailField(max_length=255, verbose_name='Email de la persona')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas de la persona')),
                ('cv_ape_pat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidopaterno', verbose_name='ID del apellido paterno')),
                ('cv_nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.catalogonombre', verbose_name='ID del nombre de la persona')),
            ],
        ),
    ]
