# Generated by Django 4.2.6 on 2023-10-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_customuser_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='usuarios',
        ),
    ]
