# Generated by Django 4.2.6 on 2023-10-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_catalogoaficion_catalogoapellidopaterno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoAficion',
        ),
        migrations.DeleteModel(
            name='CatalogoDireccion',
        ),
        migrations.DeleteModel(
            name='CatalogoGenero',
        ),
        migrations.DeleteModel(
            name='CatalogoTipoPersona',
        ),
        migrations.DeleteModel(
            name='CatalogoTrabajo',
        ),
        migrations.AlterField(
            model_name='persona',
            name='cv_ape_pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidopaterno', verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cv_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.catalogonombre', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
