# Generated by Django 4.2.6 on 2023-10-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_delete_catalogoaficion_delete_catalogodireccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoApellidoMaterno',
            fields=[
                ('cv_ape_mat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_mat', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_ape_mat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidomaterno', verbose_name='Apellido materno'),
            preserve_default=False,
        ),
    ]
