# Generated by Django 4.2.6 on 2023-10-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_catalogoapellidomaterno_persona_cv_ape_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cv_ape_mat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidomaterno', verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cv_ape_pat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidopaterno', verbose_name='Apellido paterno'),
        ),
    ]
