# Generated by Django 4.2.6 on 2023-10-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_customuser_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
    ]
