# Generated by Django 4.2.6 on 2023-10-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_remove_customuser_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.persona'),
        ),
    ]
