# Generated by Django 4.2.6 on 2023-10-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_persona_cv_ape_mat_alter_persona_cv_ape_pat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAficion',
            fields=[
                ('cv_aficion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_aficion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDireccion',
            fields=[
                ('cv_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoGenero',
            fields=[
                ('cv_genero', models.AutoField(primary_key=True, serialize=False)),
                ('ds_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTipoPersona',
            fields=[
                ('cv_tp_person', models.AutoField(primary_key=True, serialize=False)),
                ('ds_tp_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTrabajo',
            fields=[
                ('cv_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('ds_trabajo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='cv_nombre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogonombre', verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_aficion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.catalogoaficion', verbose_name='Aficion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_direccion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogodireccion', verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_genero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogogenero', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_tp_persona',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotipopersona', verbose_name='Tipo de persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cv_trabajo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotrabajo', verbose_name='Trabajo'),
        ),
    ]
