# Generated by Django 4.2.6 on 2023-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_catalogoaficion_catalogodireccion_catalogogenero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cv_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('login_usuario', models.CharField(max_length=255)),
                ('pass_usuario', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_aficion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_ape_mat',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_ape_pat',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_genero',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_tp_persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cv_trabajo',
        ),
        migrations.DeleteModel(
            name='CatalogoAficion',
        ),
        migrations.DeleteModel(
            name='CatalogoApellidoMaterno',
        ),
        migrations.DeleteModel(
            name='CatalogoApellidoPaterno',
        ),
        migrations.DeleteModel(
            name='CatalogoDireccion',
        ),
        migrations.DeleteModel(
            name='CatalogoGenero',
        ),
        migrations.DeleteModel(
            name='CatalogoNombre',
        ),
        migrations.DeleteModel(
            name='CatalogoTipoPersona',
        ),
        migrations.DeleteModel(
            name='CatalogoTrabajo',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
