# Generated by Django 4.2.6 on 2023-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_usuario_remove_persona_cv_aficion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.BooleanField(default=False),
        ),
    ]
