# Generated by Django 4.2.6 on 2023-10-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_usuario_estado_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAficiones',
            fields=[
                ('cv_aficion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_aficion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoApellidosMaterno',
            fields=[
                ('cv_ape_mat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_mat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoApellidosPaterno',
            fields=[
                ('cv_ape_pat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ape_pat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDirecciones',
            fields=[
                ('cv_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('ds_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoGeneros',
            fields=[
                ('cv_genero', models.AutoField(primary_key=True, serialize=False)),
                ('ds_genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoNombres',
            fields=[
                ('cv_nombre', models.AutoField(primary_key=True, serialize=False)),
                ('ds_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTiposPersona',
            fields=[
                ('cv_tp_person', models.AutoField(primary_key=True, serialize=False)),
                ('ds_tp_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTrabajos',
            fields=[
                ('cv_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('ds_trabajo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cv_persona', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono de la persona')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas de la persona')),
                ('cv_aficion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.catalogoaficiones', verbose_name='Aficion')),
                ('cv_ape_mat', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidosmaterno', verbose_name='Apellido materno')),
                ('cv_ape_pat', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogoapellidospaterno', verbose_name='Apellido paterno')),
                ('cv_direccion', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogodirecciones', verbose_name='Direccion')),
                ('cv_genero', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogogeneros', verbose_name='Genero')),
                ('cv_nombre', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogonombres', verbose_name='Nombre')),
                ('cv_tp_persona', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotipospersona', verbose_name='Tipo de persona')),
                ('cv_trabajo', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.catalogotrabajos', verbose_name='Trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cv_persona',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.persona', verbose_name='Nombre'),
        ),
    ]
