# Generated by Django 4.2.6 on 2023-10-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_catalogoaficiones_catalogoapellidosmaterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cv_nombre_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='security.persona', verbose_name='Persona'),
        ),
    ]
