# Generated by Django 4.2.6 on 2023-10-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_usuario_cv_nombre_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
